export const PRICING_TIERS = [
  {
    id: 'monthly',
    title: 'Monthly Subscription',
    priceDisplay: '$19',
    billingPeriod: '/ month',
    savings: null,
    target: 'Casual estimators or installers with only 1 or 2 carpet jobs a month.',
    badge: null,
    popular: false,
    gumroadUrl: 'https://veloxlogic.gumroad.com/l/CarpetEstimatorProMonthly',
    gumroadPermalink: 'CarpetEstimatorProMonthly',
    features: [
      'Interactive On-Screen Seam Takeoff',
      'Full Broadloom Cut Schedule & Seam Offsets',
      'Itemized Material & Accessories Breakdown',
      'Unbranded Client PDF Proposal Exports',
      'Cancel anytime with zero penalty',
    ],
  },
  {
    id: 'annual',
    title: 'Annual Subscription',
    priceDisplay: '$149',
    billingPeriod: '/ year',
    savings: 'Saves ~35%',
    target: 'Active residential estimators who want the cheapest ongoing rate.',
    badge: 'Save 35%',
    popular: false,
    gumroadUrl: 'https://veloxlogic.gumroad.com/l/CarpetEstimatorProAnnual',
    gumroadPermalink: 'CarpetEstimatorProAnnual',
    features: [
      'Everything in Monthly plan',
      'Equivalent to just $12.41 / month',
      'Unlimited printable PDF exports for field crews',
      'Pattern match repeat waste optimization',
      'Priority contractor support',
    ],
  },
  {
    id: 'lifetime',
    title: 'Lifetime License',
    priceDisplay: '$199',
    billingPeriod: 'one-time payment',
    savings: 'Best Long-Term Value',
    target: 'Contractors who want to buy once, write off as a tax expense, and avoid recurring charges forever.',
    badge: 'Best Value',
    popular: true,
    gumroadUrl: 'https://veloxlogic.gumroad.com/l/CarpetEstimatorPro-lifetime',
    gumroadPermalink: 'CarpetEstimatorPro-lifetime',
    features: [
      'Pay once • Own forever • No monthly fees',
      'Full unwatermarked printable PDF crew diagrams',
      'Unlimited project estimates & PDF proposal downloads',
      'Tax-deductible business expense write-off',
      'All future feature updates included',
    ],
  },
] as const;

export const PRICING = {
  PRICE_DISPLAY: "$199",
  PRICE_AMOUNT: 199,
  CURRENCY: "USD",
  OFFER_TITLE: "Lifetime License Pass",
  NO_SUBSCRIPTION: "One-Time Payment • Lifetime Updates • No Recurring Fees",
} as const;
